trigger:
- main
- hml
resources:
  repositories:
  - repository: azure-pipelines
    type: git
    name: Interligação OCC - Grupo Mult/azure-pipelines
name: $(Rev:r)
variables:
- group: QA-Application-Variables
- group: PRD-Application-Variables
jobs:
- template: docker-builder.yaml@azure-pipelines