apiVersion: apps/v1
kind: Deployment
metadata:
  name: md-product-images-integration-ms
spec:
  selector:
    matchLabels:
      app: md-product-images-integration-ms
  replicas: REPLICASPODS
  template:
    metadata:
      labels:
        app: md-product-images-integration-ms
    spec:
      containers:
      - name: md-product-images-integration-ms
        image: gru.ocir.io/grboiw7hzvhq/md-product-images-integration-ms:BUILDNUMBER
        imagePullPolicy: Always
        env:
           - name: OPENTRACING_JAEGER_SERVICE_NAME
             value: "md-product-images-integration-ms"
           - name: OPENTRACING_JAEGER_LOG_SPANS
             value: "true"
           - name: OPENTRACING_JAEGER_ENABLE-B3-PROPAGATION
             value: "true"
        ports:
        - name: sbapp
          containerPort: 8080
          protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: md-product-images-integration-ms-ingress
  namespace: interligacao-occ
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.org/mergeable-ingress-type: "minion"
spec:
  rules:
    - host: ING_HOST
      http:
        paths:
        - path: /img
          pathType: Prefix
          backend:
            service:
              name: md-product-images-integration-ms-lb
              port:
                number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: md-product-images-integration-ms-lb
  labels:
    app: md-product-images-integration-ms
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: md-product-images-integration-ms